DROP TABLE Weighing;
DROP TABLE Milking;
DROP TABLE FoodConsumption;
DROP TABLE FoodPurchase;
DROP TABLE Animal;
DROP TABLE Issue;
DROP TABLE User;
Drop TABLE Farm;

Create TABLE Farm (
    id BiGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) COLLATE latin1_bin NOT NULL,
    address VARCHAR(500) NOT NULL,
    sizeHectares INTEGER NOT NULL,
    creationDate DATETIME NOT NULL,
    CONSTRAINT  FarmPk PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE User (
    id BIGINT NOT NULL AUTO_INCREMENT,
    userName VARCHAR(60) COLLATE latin1_bin NOT NULL,
    password VARCHAR(60) NOT NULL, 
    firstName VARCHAR(60) NOT NULL,
    lastName VARCHAR(60) NOT NULL, 
    email VARCHAR(60) NOT NULL,
    role TINYINT NOT NULL,
    isEliminated BOOLEAN default false,
    farmId BIGINT NOT NULL,
    CONSTRAINT UserPK PRIMARY KEY (id),
    CONSTRAINT UserNameUniqueKey UNIQUE (userName),
    CONSTRAINT UserFarmFK FOREIGN KEY (farmId) REFERENCES Farm(id) On DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Issue (
    id BIGINT NOT NULL AUTO_INCREMENT,
    issueName VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    creationDate DATETIME NOT NULL,
    isDone BOOLEAN DEFAULT FALSE,
    createdBy BIGINT NOT NULL,
    assignedTo BIGINT NOT NULL,
    CONSTRAINT IssuePk PRIMARY KEY (id),
    CONSTRAINT createdByFK FOREIGN KEY (createdBy) REFERENCES User(id) ON DELETE CASCADE,
    CONSTRAINT assignedToFK FOREIGN KEY (assignedTo) REFERENCES User(id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Animal (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) DEFAULT NULL,
    identificationNumber BIGINT NOT NULL,
    birthDate DATETIME NOT NULL,
    isMale BOOLEAN NOT NULL,
    physicalDescription VARCHAR(250) DEFAULT NULL,
    belongsTo BIGINT NOT NULL,
    isDead BOOLEAN DEFAULT FALSE,
    CONSTRAINT AnimalPK PRIMARY KEY (id),
    CONSTRAINT belongsToFK FOREIGN KEY (belongsTo) REFERENCES Farm(id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE FoodPurchase (
    id BIGINT NOT NULL AUTO_INCREMENT,
    productName VARCHAR(100) NOT NULL,
    ingredients VARCHAR(500) DEFAULT NULL,
    purchaseDate DATETIME NOT NULL,
    supplier VARCHAR(100) DEFAULT NULL,
    kilos INTEGER NOT NULL,
    unitPrice DECIMAL(11,2) NOT NULL,
    madeBy BIGINT NOT NULL,
    CONSTRAINT FoodPurchasePK PRIMARY KEY (id),
    CONSTRAINT madeByFK FOREIGN KEY (madeBy) REFERENCES User(id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE FoodConsumption (
    id BIGINT NOT NULL AUTO_INCREMENT,
    date DATETIME NOT NULL,
    kilos INTEGER NOT NULL,
    foodBatch BIGINT NOT NULL,
    consumedBy BIGINT NOT NULL,
    CONSTRAINT FoodConsumptionPK PRIMARY KEY (id),
    CONSTRAINT foodPurchaseFK FOREIGN KEY (foodBatch) REFERENCES FoodPurchase(id) ON DELETE CASCADE,
    CONSTRAINT animalFK FOREIGN KEY (consumedBy) REFERENCES Animal(id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Weighing (
    id BIGINT NOT NULL AUTO_INCREMENT,
    date DATETIME NOT NULL,
    kilos INTEGER NOT NULL,
    madeBy BIGINT NOT NULL,
    animalWeighed BIGINT NOT NULL,
    CONSTRAINT WeighingPK PRIMARY KEY (id),
    CONSTRAINT WeighingMadeByFK FOREIGN KEY (madeBy) REFERENCES User(id) ON DELETE CASCADE,
    CONSTRAINT animalWeighedFK FOREIGN KEY (animalWeighed) REFERENCES Animal(id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Milking (
    id BIGINT NOT NULL AUTO_INCREMENT,
    date DATETIME NOT NULL,
    liters INTEGER NOT NULL,
    madeBy BIGINT NOT NULL,
    animalMilked BIGINT NOT NULL,
    CONSTRAINT MilkingPK PRIMARY KEY (id),
    CONSTRAINT MilkingMadeByFK FOREIGN KEY (madeBy) REFERENCES User(id) ON DELETE CASCADE,
    CONSTRAINT animalMilkedFK FOREIGN KEY (animalMilked) REFERENCES Animal(id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE INDEX UserIndexByUserName ON User (userName);

